version: "3.6"
services:
  postgres:
    image: postgres:11.4
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  arangodb:
    image: arangodb/arangodb:3.4.6
    restart: always
    ports:
      - "${ARANGODB_PORT}:8529"
    depends_on:
      - "postgres"
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD}
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - arangodb_data:/var/lib/arangodb
      - arangodb_apps:/var/lib/arangodb-apps

  hasura:
    # image: hasura/graphql-engine:latest
    image: hasura/graphql-engine:v1.0.0-beta.2
    ports:
      - "${HASURA_PORT}:8080"
    depends_on:
      - "arangodb"
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      ARANGODB_REMOTE_SCHEMA: http://arangodb:8529/_db/planx/api/graphql
      ARANGODB_WEBHOOK: http://arangodb:8529/_db/planx/api/hasura-webhook
      # HASURA_GRAPHQL_DATABASE_URL: postgres://john@host.docker.internal:5432/planx-actions
      # HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_PASSWORD}

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      # - ./planx.template:/etc/nginx/conf.d/planx.template
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "arangodb"
      # - "hasura"

volumes:
  postgres_data:
  arangodb_data:
  arangodb_apps:
